#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                                                               ║${NC}"
echo -e "${CYAN}║   ${GREEN}🚀 NEXUS STARTER - PROJECT SETUP${CYAN}                           ║${NC}"
echo -e "${CYAN}║                                                               ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠️  A .env file already exists.${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Setup cancelled. Your .env file was not modified.${NC}"
        exit 0
    fi
fi

# Client/Site Name
echo ""
echo -e "${BLUE}📝 SITE CONFIGURATION${NC}"
echo -e "${BLUE}─────────────────────${NC}"
read -p "Site name (e.g., Grace Community Church): " SITE_NAME
read -p "Domain (e.g., gracechurch.com): " SITE_DOMAIN

# Site Type
echo ""
echo -e "${BLUE}🏢 SITE TYPE${NC}"
echo -e "${BLUE}────────────${NC}"
echo "1) Business (leads, quotes, services)"
echo "2) Church (sermons, events, prayer requests)"
read -p "Select [1-2]: " site_type_choice

case $site_type_choice in
    2) SITE_TYPE="church" ;;
    *) SITE_TYPE="business" ;;
esac

# CMS Provider
echo ""
echo -e "${BLUE}📦 CMS PROVIDER${NC}"
echo -e "${BLUE}───────────────${NC}"
echo "1) Contentful (recommended, headless CMS)"
echo "2) Sanity (alternative headless CMS)"
echo "3) Markdown (local files, no external CMS)"
read -p "Select [1-3]: " cms_choice

case $cms_choice in
    2) CMS_PROVIDER="sanity" ;;
    3) CMS_PROVIDER="markdown" ;;
    *) CMS_PROVIDER="contentful" ;;
esac

# Form Provider
echo ""
echo -e "${BLUE}📬 FORM PROVIDER${NC}"
echo -e "${BLUE}────────────────${NC}"
echo "1) GoHighLevel (full CRM integration)"
echo "2) Simple (email notifications via Resend)"
read -p "Select [1-2]: " form_choice

case $form_choice in
    2) FORM_PROVIDER="simple" ;;
    *) FORM_PROVIDER="ghl" ;;
esac

# i18n
echo ""
echo -e "${BLUE}🌍 INTERNATIONALIZATION${NC}"
echo -e "${BLUE}───────────────────────${NC}"
read -p "Enable multi-language support? (y/N): " i18n_enabled

if [[ $i18n_enabled =~ ^[Yy]$ ]]; then
    I18N_ENABLED="true"
    echo "Available locales: en (English), es (Spanish), ko (Korean)"
    read -p "Enter locales comma-separated (e.g., en,es): " I18N_LOCALES
    I18N_LOCALES=${I18N_LOCALES:-en}
else
    I18N_ENABLED="false"
    I18N_LOCALES="en"
fi

# Generate .env file
echo ""
echo -e "${YELLOW}📄 Generating .env file...${NC}"

cat > .env << EOF
# ==============================================================================
# NEXUS STARTER - ENVIRONMENT CONFIGURATION
# Generated by setup.sh on $(date)
# ==============================================================================

# ==============================================================================
# SITE CONFIGURATION
# ==============================================================================
SITE_NAME="${SITE_NAME}"
SITE_URL=https://${SITE_DOMAIN}
SITE_DOMAIN=${SITE_DOMAIN}
SITE_TYPE=${SITE_TYPE}

# ==============================================================================
# MODE & PROVIDERS
# ==============================================================================
NEXUS_MODE=internal
CMS_PROVIDER=${CMS_PROVIDER}
FORM_PROVIDER=${FORM_PROVIDER}

# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================
I18N_ENABLED=${I18N_ENABLED}
I18N_DEFAULT_LOCALE=en
I18N_LOCALES=${I18N_LOCALES}

# ==============================================================================
# CLOUDINARY (Required)
# ==============================================================================
PUBLIC_CLOUDINARY_CLOUD_NAME=
CLOUDINARY_CLOUD_NAME=

EOF

# Add CMS-specific variables
if [ "$CMS_PROVIDER" = "contentful" ]; then
cat >> .env << EOF
# ==============================================================================
# CONTENTFUL CMS
# ==============================================================================
CONTENTFUL_SPACE_ID=
CONTENTFUL_ACCESS_TOKEN=
PUBLIC_CONTENTFUL_ACCESS_TOKEN=
CONTENTFUL_PREVIEW_TOKEN=
CONTENTFUL_MANAGEMENT_TOKEN=
CONTENTFUL_ENVIRONMENT=master

EOF
elif [ "$CMS_PROVIDER" = "sanity" ]; then
cat >> .env << EOF
# ==============================================================================
# SANITY CMS
# ==============================================================================
SANITY_PROJECT_ID=
SANITY_DATASET=production
SANITY_API_VERSION=2024-01-01
SANITY_TOKEN=

EOF
fi

# Add form-specific variables
if [ "$FORM_PROVIDER" = "ghl" ]; then
cat >> .env << EOF
# ==============================================================================
# GOHIGHLEVEL CRM
# ==============================================================================
GHL_API_KEY=
GHL_LOCATION_ID=
GHL_PIPELINE_ID=

EOF
else
cat >> .env << EOF
# ==============================================================================
# SIMPLE EMAIL FORMS (Resend)
# ==============================================================================
RESEND_API_KEY=
NOTIFY_EMAIL=
FROM_EMAIL=

EOF
fi

# Add church-specific variables
if [ "$SITE_TYPE" = "church" ]; then
cat >> .env << EOF
# ==============================================================================
# CHURCH-SPECIFIC
# ==============================================================================
CHURCH_ONLINE_ID=
TITHELY_CHURCH_ID=

EOF
fi

# Add analytics
cat >> .env << EOF
# ==============================================================================
# ANALYTICS (Optional)
# ==============================================================================
GA_MEASUREMENT_ID=
GTM_CONTAINER_ID=

# ==============================================================================
# DEVELOPMENT
# ==============================================================================
NODE_ENV=development
PORT=4321
EOF

echo -e "${GREEN}✅ .env file created!${NC}"

# Install dependencies
echo ""
read -p "Run npm install now? (Y/n): " run_install

if [[ ! $run_install =~ ^[Nn]$ ]]; then
    echo ""
    echo -e "${YELLOW}📦 Installing dependencies...${NC}"
    npm install
    echo -e "${GREEN}✅ Dependencies installed!${NC}"
fi

# Summary
echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                     SETUP COMPLETE! 🎉                        ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Configuration:${NC}"
echo -e "  Site Name:     ${CYAN}${SITE_NAME}${NC}"
echo -e "  Domain:        ${CYAN}${SITE_DOMAIN}${NC}"
echo -e "  Site Type:     ${CYAN}${SITE_TYPE}${NC}"
echo -e "  CMS Provider:  ${CYAN}${CMS_PROVIDER}${NC}"
echo -e "  Form Provider: ${CYAN}${FORM_PROVIDER}${NC}"
echo -e "  i18n Enabled:  ${CYAN}${I18N_ENABLED}${NC}"
if [ "$I18N_ENABLED" = "true" ]; then
echo -e "  Locales:       ${CYAN}${I18N_LOCALES}${NC}"
fi
echo ""
echo -e "${YELLOW}📋 Next steps:${NC}"
echo ""
echo "  1. Fill in API keys in .env file:"
if [ "$CMS_PROVIDER" = "contentful" ]; then
echo "     - Contentful: CONTENTFUL_SPACE_ID, CONTENTFUL_ACCESS_TOKEN"
elif [ "$CMS_PROVIDER" = "sanity" ]; then
echo "     - Sanity: SANITY_PROJECT_ID"
fi
echo "     - Cloudinary: PUBLIC_CLOUDINARY_CLOUD_NAME"
if [ "$FORM_PROVIDER" = "ghl" ]; then
echo "     - GoHighLevel: GHL_API_KEY, GHL_LOCATION_ID"
else
echo "     - Resend: RESEND_API_KEY, NOTIFY_EMAIL"
fi
echo ""
echo "  2. Start development server:"
echo -e "     ${CYAN}npm run dev${NC}"
echo ""
echo "  3. Open in browser:"
echo -e "     ${CYAN}http://localhost:4321${NC}"
echo ""
echo "  4. Test forms:"
echo -e "     ${CYAN}http://localhost:4321/forms-demo${NC}"
echo ""
echo "  5. Test i18n (if enabled):"
echo -e "     ${CYAN}http://localhost:4321/i18n-demo${NC}"
echo ""
echo -e "${BLUE}📚 Documentation:${NC}"
echo "  - ENV_CONFIG.md - Full environment variable guide"
echo "  - SETUP_CHECKLIST.md - Detailed setup instructions"
echo "  - README.md - Project overview"
echo ""
